export const INJECT_TOKENS_KEY = Symbol("INJECT-DECORATOR-METADATA");
export const INJECTABLE_KEY = Symbol("INJECTABLE-DECORATOR-METADATA");
export const CONTROLLER_KEY = Symbol("CONTROLLER-DECORATOR-METADATA")
export const ROUTE_KEY = Symbol('ROUTE-DECORATOR-METADATA')
export const PARAM_METADATA_KEY = Symbol('PARAM-DECORATOR-METADATA')
export const GUARD_METADATA_KEY = Symbol('GUARD-DECORATOR-METADATA')
export const INTERCEPTOR_METADATA_KEY = Symbol('INTERCEPTOR-DECORATOR-METADATA')
